[package]
name = "shift_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

component-features = { path = "../component-features"}
